package com.hrrm.famoney.infrastructure.persistence.migrations;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.io.IOUtils;

import com.hrrm.famoney.function.throwing.ThrowingBiConsumer;
import com.hrrm.famoney.function.throwing.ThrowingFunction;

public abstract class JdbcMigrationStetemnets implements AutoCloseable {

    private final Map<String, PreparedStatement> namedPreparedStatements = new HashMap<>();
    private final Connection connection;
    private URI baseURI;
    private final String basePath;
    private final ClassLoader classLoader;

    public JdbcMigrationStetemnets(final Connection connection, final String basePath, final ClassLoader classLoader) {
        super();
        this.connection = connection;
        this.basePath = basePath;
        this.classLoader = classLoader;
    }

    private URI getBaseURI() throws MigrationException {
        try {
            if (baseURI == null) {
                baseURI = IOUtils.resourceToURL(basePath,
                        classLoader)
                    .toURI();
            }
            return baseURI;
        } catch (URISyntaxException | IOException e) {
            throw new MigrationException(MessageFormat.format("Unable to get URI from base path: {0} over classpath",
                    basePath));
        }
    }

    private PreparedStatement prepareStatement(final URI uri, final int autoGeneratedKeys) throws MigrationException {
        String sql = "";
        try {
            sql = IOUtils.toString(uri,
                    StandardCharsets.UTF_8);
            return connection.prepareStatement(sql,
                    autoGeneratedKeys);
        } catch (final SQLException ex) {
            throw new MigrationException(MessageFormat.format("Cannot prepare statement from sql\n\r : {0}.",
                    sql),
                ex);
        } catch (final IOException ex) {
            throw new MigrationException(MessageFormat.format(
                    "Cannot load resource with SQL statement: {0} from classpath.",
                    uri),
                ex);
        }
    }

    protected PreparedStatement getStatement(final String path) throws MigrationException {
        return getStatement(path,
                Statement.NO_GENERATED_KEYS);
    }

    protected PreparedStatement getStatementWithGeneratedKeys(final String path) throws MigrationException {
        return getStatement(path,
                Statement.RETURN_GENERATED_KEYS);
    }

    protected PreparedStatement getStatement(final String path, final int generatedKeys) throws MigrationException {
        return namedPreparedStatements.computeIfAbsent(path,
                ThrowingFunction.sneaky(p -> prepareStatement(getBaseURI().resolve(path),
                        generatedKeys)));
    }

    @Override
    public void close() throws SQLException {
        namedPreparedStatements.forEach(ThrowingBiConsumer.sneaky((path, statement) -> statement.close()));
    }

    public Connection getConnection() {
        return connection;
    }

}
