openapi: 3.0.0
info:
  contact:
    email: karmara.roman@gmail.com
    name: Roman Smushkevich
    url: https://example.com/
  title: Accounts API
  version: 1.0.0
servers:
- url: /
tags:
- description: Accounts related requests
  name: accounts
paths:
  /accounts:
    get:
      description: Lists all accounts
      operationId: getAllAccounts
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Account'
                type: array
          description: A list of all accounts
      tags:
      - accounts
      x-tags:
      - tag: accounts
components:
  schemas:
    Account:
      example:
        name: name
        id: 0
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
      type: object
